{{- if eq .Values.secret.method "csi-driver" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secret.csiDriver.secretProviderClass }}
  namespace: {{ .Values.namespace.name }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secret.csiDriver.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "{{ .Values.secret.csiDriver.secretKey }}"
            objectAlias: "secret-key"
  secretObjects:
  - secretName: {{ include "sre-assistant.fullname" . }}-secret
    type: Opaque
    data:
    - objectName: secret-key
      key: secret-key
{{- end }}
