apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sre-assistant.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  secret-key: {{ .Values.secret.secretKey | quote }}
